export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const SET_FOCUSED_POST = 'SET_FOCUSED_POST';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const EDIT_POST_SUCCESS = 'EDIT_POST_sUCCESS';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';
