export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const ADD_POST_START = 'ADD_POST_START';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const EDIT_POST_SUCCESS = 'EDIT_POST_sUCCESS';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAIL = 'USER_LOADING_FAIL';

export const LOGOUT = 'LOGOUT';
